// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Typed wrappers for Postgres functions (client.rpc)

import 'package:supabase_flutter/supabase_flutter.dart' show Supabase;
import '../models/sessions.dart';
import '../models/songs.dart';

/// Adds a song to the calling player's personal queue.
Future<String> addSongToPlayerQueue({
  required String pSessionId,
  required String pUserId,
  required String pTitle,
  required int pDuration,
  String? pThumbnailUrl,
}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{
    'p_session_id': pSessionId,
    'p_user_id': pUserId,
    'p_title': pTitle,
    'p_duration': pDuration,
  };
  if (pThumbnailUrl != null) params['p_thumbnail_url'] = pThumbnailUrl;
  final result = await client.rpc('add_song_to_player_queue', params: params);
  return result as String;
}

/// RPC: get_vote_tally
Future<dynamic> getVoteTally({
  required String sessionUuid,
  required String songUuid,
}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{
    'session_uuid': sessionUuid,
    'song_uuid': songUuid,
  };
  final result = await client.rpc('get_vote_tally', params: params);
  return result;
}

/// Fetch a session row by join code.
Future<Session> getSessionByCode({required String pCode}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{'p_code': pCode};
  final result = await client.rpc('get_session_by_code', params: params);
  return Session.fromJson((result as Map).cast<String, dynamic>());
}

/// All songs in a session, in queue order.
Future<List<Song>> listSessionSongs({
  required String pSessionId,
  DateTime? pSince,
}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{'p_session_id': pSessionId};
  if (pSince != null) params['p_since'] = pSince.toIso8601String();
  final result = await client.rpc('list_session_songs', params: params);
  return (result as List)
      .map((j) => Song.fromJson((j as Map).cast<String, dynamic>()))
      .toList();
}

/// Clears all queues in a session.
Future<void> resetSession({required String pSessionId}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{'p_session_id': pSessionId};
  await client.rpc('reset_session', params: params);
}

/// Liveness probe with no arguments.
Future<bool> heartbeat() async {
  final client = Supabase.instance.client;
  final result = await client.rpc('heartbeat');
  return result as bool;
}

/// RPC: queue_length
Future<int> queueLength({required String pSessionId}) async {
  final client = Supabase.instance.client;
  final params = <String, dynamic>{'p_session_id': pSessionId};
  final result = await client.rpc('queue_length', params: params);
  return (result as num).toInt();
}
