import 'package:supabase_client_gen/src/contract_loader.dart';
import 'package:supabase_client_gen/src/generator.dart';
import 'package:test/test.dart';

/// Behaviour tests that pin the Phase-1 correctness guarantees independently of
/// the golden snapshots, so a regression names the broken contract directly.
void main() {
  final files = ClientGenerator(
    loadContract('test/fixtures/edge_cases.supabase.yaml'),
  ).generate();

  String repo(String name) => files['repositories/$name']!;

  test('non-id primary key drives update/delete/stream', () {
    final w = repo('widgets_repository.dart');
    expect(w, contains('update(String widgetId'));
    expect(w, contains(".eq('widget_id', widgetId)"));
    expect(w, contains('delete(String widgetId'));
    expect(w, contains(".stream(primaryKey: ['widget_id'])"));
    expect(w, isNot(contains(".eq('id', id)")));
  });

  test('workspace-scoped table keeps workspaceId filtering', () {
    final w = repo('widgets_repository.dart');
    expect(w, contains('required String workspaceId'));
    expect(w, contains(".eq('workspace_id', workspaceId)"));
  });

  test('global realtime read-only table gets an unscoped repo + stream', () {
    expect(files.containsKey('repositories/announcements_repository.dart'),
        isTrue);
    final a = repo('announcements_repository.dart');
    expect(a, contains('Stream<List<Announcement>> stream()'));
    expect(a, isNot(contains('workspaceId')));
    // read-only: no insert/update/delete methods
    expect(a, isNot(contains('Future<Announcement> insert')));
  });

  test('fully read-only non-realtime table gets no repository', () {
    expect(
        files.containsKey('repositories/audit_log_repository.dart'), isFalse);
  });

  test('_ies singularization (categories -> Category)', () {
    expect(files.containsKey('models/categories.dart'), isTrue);
    expect(files['models/categories.dart'],
        contains('class Category extends Equatable'));
  });

  test('reserved-word enum value is escaped', () {
    expect(files['enums/enums.dart'], contains(r'$new'));
  });

  test('edge function runtime scalar is not emitted as a function', () {
    final ef = files['edge_functions/edge_functions.dart']!;
    expect(ef, contains('resolveWidget'));
    expect(ef, isNot(contains('runtime(')));
  });

  group('storage', () {
    final s = files['storage/storage.dart']!;

    test('emits a typed client per bucket', () {
      expect(s, contains('class AvatarsBucket'));
      expect(s, contains('class DocumentsBucket'));
    });

    test('public bucket exposes getPublicUrl, private exposes signed URLs', () {
      expect(s, contains('String getPublicUrl(String path)'));
      expect(s, contains('Future<String> createSignedUrl('));
    });

    test('carries MIME + size limits from the contract', () {
      expect(
          s,
          contains(
              "static const List<String> allowedMimeTypes = ['image/png', 'image/jpeg']"));
      expect(s,
          contains('static const int? fileSizeLimitBytes = 5242880')); // 5 MB
    });
  });

  test('every generated file carries the do-not-edit provenance header', () {
    for (final content in files.values) {
      expect(content, startsWith('// GENERATED by supabase_client_gen'));
    }
  });
}
