/// Behavior tests for the CONTRACT.md Markdown projection.
///
/// Byte-level coverage lives in the goldens (every fixture renders a
/// CONTRACT.md); these tests pin the semantic rules: summary pass-through,
/// view badges, PK/enum notes, optional-arg markers, section omission and
/// determinism.
library;

import 'package:supabase_client_gen/supabase_client_gen.dart';
import 'package:test/test.dart';

const _base = '''
contract:
  name: md_test_contract
  version: "0.2.0"
  date: "2026-06-10"

project:
  remote:
    name: md_test
    ref: mdtestref0000000

auth:
  provider: supabase
  planned_sign_in_methods:
    - email

data_model:
  public:
    things:
      ownership: workspace
      primary_key: id
      description: Items a user tracks.
      fields:
        id: uuid
        workspace_id: uuid
        category: thing_category
        notes: text
      nullable_fields:
        - notes
      enum_values:
        thing_category: [device, document, other]
      client_access:
        select: member_of_workspace
        insert: member_of_workspace

    things_overview:
      kind: view
      ownership: workspace
      primary_key: [id, workspace_id]
      fields:
        id: uuid
        workspace_id: uuid
''';

const _full = '''
$_base
rpc_functions:
  add_note:
    description: Appends a note.
    args:
      p_thing_id: uuid
      p_pinned: boolean
    optional_args: [p_pinned]
    returns: uuid
  heartbeat:
    returns: boolean

edge_functions:
  runtime: deno
  resolve_thing:
    method: POST
    description: Resolve a thing from a query.
    required_request_fields: [query]
    optional_request_fields: [workspace_id]

storage:
  buckets:
    avatars:
      public: true
      allowed_mime_types: [image/png]
      file_size_limit_mb: 5

realtime:
  publication:
    allowed_tables:
      - public.things
  events:
    thing_changed:
      source: public.things
      audience: authenticated
''';

String render(String yaml, {String? summary}) {
  final contract = loadContractFromString(
    summary == null ? yaml : '$yaml\nsummary: |\n  $summary\n',
  );
  return emitContractMarkdown(contract);
}

void main() {
  group('CONTRACT.md emitter', () {
    test('header carries name, version, date and project ref', () {
      final md = render(_full);
      expect(md, startsWith('<!-- GENERATED by supabase_client_gen'));
      expect(md, contains('# md_test_contract v0.2.0'));
      expect(
        md,
        contains('`2026-06-10` · project `md_test` · ref `mdtestref0000000`'),
      );
    });

    test('output is deterministic across renders', () {
      expect(render(_full), equals(render(_full)));
    });

    test('summary is carried 1:1 when present, omitted when absent', () {
      final without = render(_full);
      expect(without, isNot(contains('Round-robin')));
      final with_ = render(_full, summary: 'Round-robin **queues**.');
      expect(with_, contains('Round-robin **queues**.'));
    });

    test('tables render fields with PK and enum notes', () {
      final md = render(_full);
      expect(md, contains('## Tables'));
      expect(md, contains('### things'));
      expect(md, contains('Items a user tracks.'));
      expect(md, contains('| Field | Type | Null | Notes |'));
      expect(md, contains('| id | uuid |  | PK |'));
      expect(
        md,
        contains('| category | thing_category |  | '
            'enum(device, document, other) |'),
      );
      expect(md, contains('| notes | text | ✓ |  |'));
    });

    test('access line joins declared client_access with dots', () {
      final md = render(_full);
      expect(
        md,
        contains('`select: member_of_workspace · insert: member_of_workspace`'),
      );
    });

    test('views carry a badge and composite PK marks every key column', () {
      final md = render(_full);
      expect(md, contains('### things_overview `view`'));
      // Both composite key parts are marked PK.
      final viewSection = md.substring(md.indexOf('### things_overview'));
      expect(viewSection, contains('| id | uuid |  | PK |'));
      expect(viewSection, contains('| workspace_id | uuid |  | PK |'));
    });

    test('rpc signature marks optional args and shows returns', () {
      final md = render(_full);
      expect(md, contains('## RPC Functions'));
      expect(
        md,
        contains('`add_note(p_thing_id: uuid, p_pinned?: boolean) → uuid`'),
      );
      expect(md, contains('Appends a note.'));
      expect(md, contains('`heartbeat() → boolean`'));
    });

    test('edge functions render method, fields and description', () {
      final md = render(_full);
      expect(md, contains('## Edge Functions'));
      expect(md, contains('`POST resolve_thing(query, workspace_id?)`'));
      expect(md, contains('Resolve a thing from a query.'));
    });

    test('realtime and storage sections are compact', () {
      final md = render(_full);
      expect(md, contains('## Realtime'));
      expect(md, contains('Publication: `public.things`'));
      expect(
        md,
        contains('- `thing_changed` ← `public.things` '
            '(audience: authenticated)'),
      );
      expect(md, contains('## Storage'));
      expect(md, contains('- `avatars` — public · image/png · max 5 MB'));
    });

    test('empty sections are omitted entirely', () {
      final md = render(_base);
      expect(md, isNot(contains('## RPC Functions')));
      expect(md, isNot(contains('## Edge Functions')));
      expect(md, isNot(contains('## Realtime')));
      expect(md, isNot(contains('## Storage')));
    });

    test('renderFormatted includes CONTRACT.md', () {
      final contract = loadContractFromString(_full);
      final files = renderFormatted(contract);
      expect(files.keys, contains('CONTRACT.md'));
      expect(files['CONTRACT.md'], equals(emitContractMarkdown(contract)));
    });

    test('loader rejects a non-string summary', () {
      expect(
        () => loadContractFromString('$_base\nsummary: [not, a, string]\n'),
        throwsA(
          isA<ContractError>().having(
            (e) => e.message,
            'message',
            contains('summary'),
          ),
        ),
      );
    });
  });
}
