// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.attachments
// Access: select=member_of_workspace insert=member_of_workspace update=edge_function_only delete=member_of_workspace

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/attachments.dart';

class AttachmentRepository {
  final SupabaseClient _client;
  const AttachmentRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Attachment>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('attachments').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Attachment.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<Attachment> insert(Map<String, dynamic> data) async {
    final row = await _client
        .from('attachments')
        .insert(data)
        .select()
        .single();
    return Attachment.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String id) async {
    await _client.from('attachments').delete().eq('id', id);
  }
}
