// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.knowledge_articles
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=member_of_workspace

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/knowledge_articles.dart';

class KnowledgeArticleRepository {
  final SupabaseClient _client;
  const KnowledgeArticleRepository(this._client);

  /// Select: member_of_workspace
  Future<List<KnowledgeArticle>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('knowledge_articles').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => KnowledgeArticle.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<KnowledgeArticle> insert(Map<String, dynamic> data) async {
    final row = await _client
        .from('knowledge_articles')
        .insert(data)
        .select()
        .single();
    return KnowledgeArticle.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<KnowledgeArticle> update(
    String articleId,
    Map<String, dynamic> data,
  ) async {
    final row = await _client
        .from('knowledge_articles')
        .update(data)
        .eq('article_id', articleId)
        .select()
        .single();
    return KnowledgeArticle.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String articleId) async {
    await _client
        .from('knowledge_articles')
        .delete()
        .eq('article_id', articleId);
  }
}
