// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.notifications
// Access: select=member_of_workspace insert=edge_function_only update=edge_function_only delete=edge_function_only
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/notifications.dart';

class NotificationRepository {
  final SupabaseClient _client;
  const NotificationRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Notification>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('notifications').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Notification.fromJson(j)).toList();
  }

  /// Realtime stream of changes to this table.
  Stream<List<Notification>> stream({required String workspaceId}) {
    return _client
        .from('notifications')
        .stream(primaryKey: ['id'])
        .eq('workspace_id', workspaceId)
        .map(
          (records) => (records as List)
              .map((j) => Notification.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
