// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.profiles
// Access: select=own_profile insert=own_profile update=own_profile delete=edge_function_only

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/profiles.dart';

class ProfileRepository {
  final SupabaseClient _client;
  const ProfileRepository(this._client);

  /// Select: own_profile
  Future<List<Profile>> select({int limit = 50, int offset = 0}) async {
    var query = _client.from('profiles').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Profile.fromJson(j)).toList();
  }

  /// Insert: own_profile
  Future<Profile> insert(Map<String, dynamic> data) async {
    final row = await _client.from('profiles').insert(data).select().single();
    return Profile.fromJson(row);
  }

  /// Update: own_profile
  Future<Profile> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('profiles')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Profile.fromJson(row);
  }
}
