// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

export 'profiles_repository.dart';
export 'workspaces_repository.dart';
export 'workspace_members_repository.dart';
export 'customers_repository.dart';
export 'tickets_repository.dart';
export 'ticket_comments_repository.dart';
export 'tags_repository.dart';
export 'knowledge_articles_repository.dart';
export 'attachments_repository.dart';
export 'notifications_repository.dart';
