// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.tickets
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=owner
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/tickets.dart';

class TicketRepository {
  final SupabaseClient _client;
  const TicketRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Ticket>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('tickets').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Ticket.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<Ticket> insert(Map<String, dynamic> data) async {
    final row = await _client.from('tickets').insert(data).select().single();
    return Ticket.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<Ticket> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('tickets')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Ticket.fromJson(row);
  }

  /// Delete: owner
  Future<void> delete(String id) async {
    await _client.from('tickets').delete().eq('id', id);
  }

  /// Realtime stream of changes to this table.
  Stream<List<Ticket>> stream({required String workspaceId}) {
    return _client
        .from('tickets')
        .stream(primaryKey: ['id'])
        .eq('workspace_id', workspaceId)
        .map(
          (records) => (records as List)
              .map((j) => Ticket.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
