// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.ticket_comments
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=member_of_workspace
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/ticket_comments.dart';

class TicketCommentRepository {
  final SupabaseClient _client;
  const TicketCommentRepository(this._client);

  /// Select: member_of_workspace
  Future<List<TicketComment>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('ticket_comments').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => TicketComment.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<TicketComment> insert(Map<String, dynamic> data) async {
    final row = await _client
        .from('ticket_comments')
        .insert(data)
        .select()
        .single();
    return TicketComment.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<TicketComment> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('ticket_comments')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return TicketComment.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String id) async {
    await _client.from('ticket_comments').delete().eq('id', id);
  }

  /// Realtime stream of changes to this table.
  Stream<List<TicketComment>> stream({required String workspaceId}) {
    return _client
        .from('ticket_comments')
        .stream(primaryKey: ['id'])
        .eq('workspace_id', workspaceId)
        .map(
          (records) => (records as List)
              .map((j) => TicketComment.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
