// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.workspaces
// Access: select=member_of_workspace insert=authenticated update=owner delete=owner

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/workspaces.dart';

class WorkspaceRepository {
  final SupabaseClient _client;
  const WorkspaceRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Workspace>> select({int limit = 50, int offset = 0}) async {
    var query = _client.from('workspaces').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Workspace.fromJson(j)).toList();
  }

  /// Insert: authenticated
  Future<Workspace> insert(Map<String, dynamic> data) async {
    final row = await _client.from('workspaces').insert(data).select().single();
    return Workspace.fromJson(row);
  }

  /// Update: owner
  Future<Workspace> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('workspaces')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Workspace.fromJson(row);
  }

  /// Delete: owner
  Future<void> delete(String id) async {
    await _client.from('workspaces').delete().eq('id', id);
  }
}
