// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.workspace_members
// Access: select=member_of_workspace insert=owner update=owner delete=owner

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/workspace_members.dart';

class WorkspaceMemberRepository {
  final SupabaseClient _client;
  const WorkspaceMemberRepository(this._client);

  /// Select: member_of_workspace
  Future<List<WorkspaceMember>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('workspace_members').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => WorkspaceMember.fromJson(j)).toList();
  }

  /// Insert: owner
  Future<WorkspaceMember> insert(Map<String, dynamic> data) async {
    final row = await _client
        .from('workspace_members')
        .insert(data)
        .select()
        .single();
    return WorkspaceMember.fromJson(row);
  }

  /// Update: owner
  Future<WorkspaceMember> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('workspace_members')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return WorkspaceMember.fromJson(row);
  }

  /// Delete: owner
  Future<void> delete(String id) async {
    await _client.from('workspace_members').delete().eq('id', id);
  }
}
