// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

enum WorkspacePlan {
  free,
  pro,
  enterprise;

  static WorkspacePlan fromString(String value) {
    return WorkspacePlan.values.firstWhere(
      (e) => e.name == value,
      orElse: () => WorkspacePlan.free,
    );
  }
}

enum TicketStatus {
  open,
  pending,
  resolved,
  closed;

  static TicketStatus fromString(String value) {
    return TicketStatus.values.firstWhere(
      (e) => e.name == value,
      orElse: () => TicketStatus.open,
    );
  }
}

enum TicketPriority {
  low,
  normal,
  high,
  urgent;

  static TicketPriority fromString(String value) {
    return TicketPriority.values.firstWhere(
      (e) => e.name == value,
      orElse: () => TicketPriority.low,
    );
  }
}
