// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

enum WidgetStatus {
  $new,
  active,
  retired;

  static WidgetStatus fromString(String value) {
    return WidgetStatus.values.firstWhere(
      (e) => e.name == value,
      orElse: () => WidgetStatus.$new,
    );
  }
}
