/// Code generator: docs/contracts/supabase.yaml → Dart client code.
library;

import 'contract.dart';

class ClientGenerator {
  final SupabaseContract contract;

  ClientGenerator(this.contract);

  Map<String, String> generate() {
    final files = <String, String>{};

    for (final entry in contract.publicTables.entries) {
      final tableName = entry.key;
      final className = _className(tableName);
      files['models/$tableName.dart'] = _generateModel(
        tableName,
        className,
        entry.value,
      );
    }

    files['enums/enums.dart'] = _generateAllEnums();

    for (final entry in contract.publicTables.entries) {
      if (_hasRepository(entry.key, entry.value)) {
        final className = _className(entry.key);
        files['repositories/${entry.key}_repository.dart'] =
            _generateRepository(entry.key, className, entry.value);
      }
    }

    if (contract.edgeFunctions != null) {
      final clientFuncs = _clientInvokedFunctions();
      if (clientFuncs.isNotEmpty) {
        files['edge_functions/edge_functions.dart'] = _generateEdgeFunctions(
          clientFuncs,
        );
      }
    }

    if (contract.rpcFunctions != null && contract.rpcFunctions!.isNotEmpty) {
      files['rpc/rpc.dart'] = _generateRpc(contract.rpcFunctions!);
    }

    if (contract.storage != null && contract.storage!.buckets.isNotEmpty) {
      files['storage/storage.dart'] = _generateStorage(contract.storage!);
    }

    files['models/models.dart'] = _barrel(
      contract.publicTables.keys.map((t) => "export '$t.dart';"),
    );
    files['repositories/repositories.dart'] = _barrel(
      contract.publicTables.entries
          .where((e) => _hasRepository(e.key, e.value))
          .map((e) => "export '${e.key}_repository.dart';"),
    );

    return files;
  }

  // ── Models ──────────────────────────────────────────────────────────

  String _generateModel(String tableName, String className, TableConfig table) {
    final b = StringBuffer();
    final fields = table.fields.keys.toList();

    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln('// Table: public.$tableName');
    b.writeln();
    b.writeln("import 'package:equatable/equatable.dart';");
    if (_hasEnumFields(table)) b.writeln("import '../enums/enums.dart';");
    b.writeln();
    b.writeln('class $className extends Equatable {');
    b.writeln('  const $className({');
    for (final f in fields) {
      if (_isNullable(tableName, f)) {
        b.writeln('    this.${_camel(f)},');
      } else {
        b.writeln('    required this.${_camel(f)},');
      }
    }
    b.writeln('  });');
    b.writeln();

    for (final f in fields) {
      final type = _dartType(table, f);
      final nullable = _isNullable(tableName, f) ? '?' : '';
      b.writeln('  final $type$nullable ${_camel(f)};');
    }
    b.writeln();

    b.writeln('  $className copyWith({');
    for (final f in fields) {
      b.writeln('    ${_dartType(table, f)}? ${_camel(f)},');
    }
    b.writeln('  }) {');
    b.writeln('    return $className(');
    for (final f in fields) {
      final c = _camel(f);
      b.writeln('      $c: $c ?? this.$c,');
    }
    b.writeln('    );');
    b.writeln('  }');
    b.writeln();

    b.writeln('  factory $className.fromJson(Map<String, dynamic> json) {');
    b.writeln('    return $className(');
    for (final f in fields) {
      b.writeln('      ${_camel(f)}: ${_fromJsonExpr(table, f, tableName)},');
    }
    b.writeln('    );');
    b.writeln('  }');
    b.writeln();

    b.writeln('  Map<String, dynamic> toJson() {');
    b.writeln('    return {');
    for (final f in fields) {
      b.writeln("      '$f': ${_toJsonExpr(table, f, tableName)},");
    }
    b.writeln('    };');
    b.writeln('  }');
    b.writeln();

    b.writeln('  @override');
    b.writeln(
      '  List<Object?> get props => [${fields.map(_camel).join(', ')}];',
    );
    b.writeln('}');

    return b.toString();
  }

  String _fromJsonExpr(TableConfig table, String fieldName, String tableName) {
    final dt = _dartType(table, fieldName);
    final key = "json['$fieldName']";
    final nullable = _isNullable(tableName, fieldName);

    if (dt == 'DateTime') {
      return nullable
          ? "$key != null ? DateTime.parse($key as String) : null"
          : "$key != null ? DateTime.parse($key as String) : DateTime.now()";
    }
    if (dt == 'int') {
      return nullable
          ? "($key as num?)?.toInt()"
          : "($key as num?)?.toInt() ?? 0";
    }
    if (dt == 'double') {
      return nullable
          ? "($key as num?)?.toDouble()"
          : "($key as num?)?.toDouble() ?? 0.0";
    }
    if (dt == 'bool') {
      return nullable ? "$key as bool?" : "$key as bool? ?? false";
    }
    if (dt == 'Map<String, dynamic>') {
      return nullable
          ? "$key as Map<String, dynamic>?"
          : "($key as Map<String, dynamic>?) ?? {}";
    }
    if (dt == 'List<double>') {
      return nullable
          ? "$key as List<double>?"
          : "($key as List<dynamic>?)?.map((e) => (e as num).toDouble()).toList() ?? []";
    }
    if (dt == 'List<String>') {
      return nullable
          ? "($key as List<dynamic>?)?.cast<String>()"
          : "($key as List<dynamic>?)?.cast<String>() ?? const []";
    }
    if (table.isEnumField(fieldName)) {
      final enumName = _pascal(table.fields[fieldName]!);
      return nullable
          ? "$key != null ? $enumName.fromString($key as String) : null"
          : "$enumName.fromString($key as String? ?? '')";
    }
    return nullable ? "$key as String?" : "$key as String? ?? ''";
  }

  String _toJsonExpr(TableConfig table, String fieldName, String tableName) {
    final dt = _dartType(table, fieldName);
    final c = _camel(fieldName);
    final nullable = _isNullable(tableName, fieldName);
    if (dt == 'DateTime') {
      return nullable ? '$c?.toIso8601String()' : '$c.toIso8601String()';
    }
    if (table.isEnumField(fieldName)) return nullable ? '$c?.name' : '$c.name';
    return c;
  }

  // ── Enums ───────────────────────────────────────────────────────────

  String _generateAllEnums() {
    final all = <String, List<String>>{};
    for (final t in contract.publicTables.values) {
      if (t.enumValues != null) all.addAll(t.enumValues!);
    }
    final b = StringBuffer();
    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln();
    for (final entry in all.entries) {
      final name = _pascal(entry.key);
      b.writeln('enum $name {');
      for (final v in entry.value) {
        b.writeln('  ${_safeEnum(v)},');
      }
      b.writeln(';');
      b.writeln();
      b.writeln('  static $name fromString(String value) {');
      b.writeln('    return $name.values.firstWhere(');
      b.writeln('      (e) => e.name == value,');
      b.writeln('      orElse: () => $name.${_safeEnum(entry.value.first)},');
      b.writeln('    );');
      b.writeln('  }');
      b.writeln('}');
      b.writeln();
    }
    return b.toString();
  }

  // ── Repositories ────────────────────────────────────────────────────

  bool _isReadOnly(TableConfig table) {
    final a = table.clientAccess;
    if (a == null) return true;
    final ins = a['insert'] ?? '',
        upd = a['update'] ?? '',
        del = a['delete'] ?? '';
    return ins == 'edge_function_only' &&
        upd == 'edge_function_only' &&
        del == 'edge_function_only';
  }

  /// A repository is emitted when the table is client-mutable OR exposes a
  /// realtime stream (so read-only realtime tables still get a `.stream()`).
  bool _hasRepository(String tableName, TableConfig table) {
    return !_isReadOnly(table) ||
        contract.realtimePublicTables.contains(tableName);
  }

  /// Workspace scoping is driven by the actual presence of a `workspace_id`
  /// column — you can only filter by a column that exists. Tables without it
  /// (global, user-owned, the workspaces table itself) get unscoped queries.
  bool _isWorkspaceScoped(TableConfig table) =>
      table.fields.containsKey('workspace_id');

  String _generateRepository(
    String tableName,
    String className,
    TableConfig table,
  ) {
    final a = table.clientAccess ?? {};
    final sel = a['select'] ?? 'none';
    final ins = a['insert'] ?? 'none';
    final upd = a['update'] ?? 'none';
    final del = a['delete'] ?? 'none';
    final canIns = ins != 'edge_function_only' && ins != 'none';
    final canUpd = upd != 'edge_function_only' && upd != 'none';
    final canDel = del != 'edge_function_only' && del != 'none';
    final hasRealtime = contract.realtimePublicTables.contains(tableName);
    final wsScoped = _isWorkspaceScoped(table);
    // Composite keys: every key column becomes a required parameter and one
    // chained `.eq()`. The single-column form is the degenerate case.
    final pks = table.primaryKey;
    final pkParams = pks.map((c) => 'String ${_camel(c)}').join(', ');
    final pkEqChain = pks.map((c) => ".eq('$c', ${_camel(c)})").join();
    final pkList = pks.map((c) => "'$c'").join(', ');

    final b = StringBuffer();
    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln('// Table: public.$tableName');
    b.writeln('// Access: select=$sel insert=$ins update=$upd delete=$del');
    if (hasRealtime) b.writeln('// Realtime: enabled');
    b.writeln();
    b.writeln("import 'dart:async';");
    // `show` keeps generated table models (e.g. Session, User) from clashing
    // with the gotrue types of the same name re-exported by supabase_flutter.
    b.writeln(
      "import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;",
    );
    b.writeln("import '../models/$tableName.dart';");
    b.writeln();
    b.writeln('class ${className}Repository {');
    b.writeln('  final SupabaseClient _client;');
    b.writeln('  const ${className}Repository(this._client);');
    b.writeln();

    if (sel != 'none') {
      final needsWs = wsScoped;
      b.writeln('  /// Select: $sel');
      b.writeln('  Future<List<$className>> select({');
      if (needsWs) b.writeln('    required String workspaceId,');
      b.writeln('    int limit = 50,');
      b.writeln('    int offset = 0,');
      b.writeln('  }) async {');
      b.writeln("    var query = _client.from('$tableName').select();");
      if (needsWs) {
        b.writeln("    query = query.eq('workspace_id', workspaceId);");
      }
      b.writeln(
        '    final data = await query.limit(limit).range(offset, offset + limit - 1);',
      );
      b.writeln(
        '    return (data as List).map((j) => $className.fromJson(j)).toList();',
      );
      b.writeln('  }');
      b.writeln();
    }

    if (canIns) {
      b.writeln('  /// Insert: $ins');
      b.writeln(
        '  Future<$className> insert(Map<String, dynamic> data) async {',
      );
      b.writeln(
        "    final row = await _client.from('$tableName').insert(data).select().single();",
      );
      b.writeln('    return $className.fromJson(row);');
      b.writeln('  }');
      b.writeln();
    }

    if (canUpd) {
      b.writeln('  /// Update: $upd');
      b.writeln(
        '  Future<$className> update($pkParams, Map<String, dynamic> data) async {',
      );
      b.writeln(
        "    final row = await _client.from('$tableName').update(data)$pkEqChain.select().single();",
      );
      b.writeln('    return $className.fromJson(row);');
      b.writeln('  }');
      b.writeln();
    }

    if (canDel) {
      b.writeln('  /// Delete: $del');
      b.writeln('  Future<void> delete($pkParams) async {');
      b.writeln(
        "    await _client.from('$tableName').delete()$pkEqChain;",
      );
      b.writeln('  }');
      b.writeln();
    }

    if (hasRealtime) {
      b.writeln('  /// Realtime stream of changes to this table.');
      if (wsScoped) {
        b.writeln('  Stream<List<$className>> stream({');
        b.writeln("    required String workspaceId,");
        b.writeln('  }) {');
        b.writeln("    return _client");
        b.writeln("        .from('$tableName')");
        b.writeln("        .stream(primaryKey: [$pkList])");
        b.writeln("        .eq('workspace_id', workspaceId)");
        b.writeln('        .map((records) => (records as List)');
        b.writeln(
          '            .map((j) => $className.fromJson(j as Map<String, dynamic>))',
        );
        b.writeln('            .toList());');
        b.writeln('  }');
      } else {
        b.writeln('  Stream<List<$className>> stream() {');
        b.writeln("    return _client");
        b.writeln("        .from('$tableName')");
        b.writeln("        .stream(primaryKey: [$pkList])");
        b.writeln('        .map((records) => (records as List)');
        b.writeln(
          '            .map((j) => $className.fromJson(j as Map<String, dynamic>))',
        );
        b.writeln('            .toList());');
        b.writeln('  }');
      }
      b.writeln();
    }

    b.writeln('}');
    return b.toString();
  }

  // ── Storage ─────────────────────────────────────────────────────────

  String _generateStorage(StorageConfig storage) {
    final b = StringBuffer();
    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln('// Typed storage bucket clients');
    b.writeln();
    b.writeln("import 'dart:typed_data';");
    b.writeln("import 'package:supabase_flutter/supabase_flutter.dart';");
    b.writeln();

    for (final entry in storage.buckets.entries) {
      _writeBucketClient(b, entry.key, entry.value);
      b.writeln();
    }
    return b.toString();
  }

  void _writeBucketClient(StringBuffer b, String bucketName, StorageBucket bk) {
    final className = '${_pascal(bucketName)}Bucket';
    final mimes = bk.allowedMimeTypes;
    final limitBytes =
        bk.fileSizeLimitMb != null ? bk.fileSizeLimitMb! * 1024 * 1024 : null;

    b.writeln('/// Typed client for the `$bucketName` storage bucket.');
    b.writeln('class $className {');
    b.writeln("  static const String name = '$bucketName';");
    b.writeln('  static const bool isPublic = ${bk.public};');
    final mimeList = mimes.map((m) => "'$m'").join(', ');
    b.writeln('  static const List<String> allowedMimeTypes = [$mimeList];');
    b.writeln(
      '  static const int? fileSizeLimitBytes = ${limitBytes ?? 'null'};',
    );
    b.writeln();
    b.writeln('  final SupabaseClient _client;');
    b.writeln('  const $className(this._client);');
    b.writeln();
    b.writeln("  StorageFileApi get _bucket => _client.storage.from(name);");
    b.writeln();

    // upload
    b.writeln(
        '  /// Uploads [bytes] to [path], validating MIME type and size.');
    b.writeln(
      '  Future<String> upload(String path, Uint8List bytes, {String? contentType, bool upsert = true}) async {',
    );
    b.writeln('    _validate(bytes, contentType);');
    b.writeln('    return _bucket.uploadBinary(');
    b.writeln('      path,');
    b.writeln('      bytes,');
    b.writeln(
      '      fileOptions: FileOptions(contentType: contentType, upsert: upsert),',
    );
    b.writeln('    );');
    b.writeln('  }');
    b.writeln();

    // download
    b.writeln('  /// Downloads the object at [path].');
    b.writeln(
      '  Future<Uint8List> download(String path) => _bucket.download(path);',
    );
    b.writeln();

    // url access
    if (bk.public) {
      b.writeln('  /// Public URL for [path] (this bucket is public).');
      b.writeln(
        '  String getPublicUrl(String path) => _bucket.getPublicUrl(path);',
      );
    } else {
      b.writeln('  /// Time-limited signed URL for [path] (private bucket).');
      b.writeln(
        '  Future<String> createSignedUrl(String path, {int expiresIn = 3600}) =>',
      );
      b.writeln('      _bucket.createSignedUrl(path, expiresIn);');
    }
    b.writeln();

    // remove
    b.writeln('  /// Removes the objects at [paths].');
    b.writeln(
      '  Future<List<FileObject>> remove(List<String> paths) => _bucket.remove(paths);',
    );
    b.writeln();

    // validation
    b.writeln('  void _validate(Uint8List bytes, String? contentType) {');
    b.writeln(
      '    if (allowedMimeTypes.isNotEmpty && contentType != null && !allowedMimeTypes.contains(contentType)) {',
    );
    b.writeln('      throw ArgumentError(');
    b.writeln(
      "        'Content type \$contentType is not allowed for bucket \$name. Allowed: \$allowedMimeTypes',",
    );
    b.writeln('      );');
    b.writeln('    }');
    b.writeln(
      '    if (fileSizeLimitBytes != null && bytes.length > fileSizeLimitBytes!) {',
    );
    b.writeln('      throw ArgumentError(');
    b.writeln(
      "        'File size \${bytes.length} bytes exceeds the \$fileSizeLimitBytes byte limit for bucket \$name',",
    );
    b.writeln('      );');
    b.writeln('    }');
    b.writeln('  }');
    b.writeln('}');
  }

  // ── Edge Functions ──────────────────────────────────────────────────

  Map<String, EdgeFunctionConfig> _clientInvokedFunctions() {
    final result = <String, EdgeFunctionConfig>{};
    if (contract.edgeFunctions == null) return result;
    for (final entry in contract.edgeFunctions!.entries) {
      if (entry.key == 'runtime') continue;
      result[entry.key] = entry.value;
    }
    return result;
  }

  String _generateEdgeFunctions(Map<String, EdgeFunctionConfig> functions) {
    final b = StringBuffer();
    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln('// Client-invoked edge functions');
    b.writeln();
    b.writeln("import 'package:supabase_flutter/supabase_flutter.dart';");
    b.writeln();

    for (final entry in functions.entries) {
      final fnName = entry.key;
      final fn = entry.value;
      final camel = _camel(fnName);

      // Collect all params from required + optional fields.
      final reqParams =
          fn.requiredFields.map((f) => _Param(f, _camel(f), true)).toList();
      final optParams =
          fn.optionalFields.map((f) => _Param(f, _camel(f), false)).toList();
      final allParams = [...reqParams, ...optParams];
      final hasParams = allParams.isNotEmpty;

      b.writeln('/// ${fn.description ?? 'Edge Function: $fnName'}');
      if (hasParams) {
        b.writeln('Future<Map<String, dynamic>> $camel({');
        for (final p in allParams) {
          final type = _fnParamType('text');
          final decl = p.required
              ? 'required $type ${p.dartName}'
              : '$type? ${p.dartName}';
          b.writeln('  $decl,');
        }
        b.writeln('}) async {');
      } else {
        b.writeln('Future<Map<String, dynamic>> $camel() async {');
      }
      b.writeln('  final client = Supabase.instance.client;');
      b.writeln('  final response = await client.functions.invoke(');
      b.writeln("    '$fnName',");
      b.writeln('    method: HttpMethod.${fn.method.toLowerCase()},');
      if (hasParams) {
        b.writeln('    body: {');
        for (final p in allParams) {
          b.writeln("      '${p.name}': ${p.dartName},");
        }
        b.writeln('    },');
      }
      b.writeln('  );');
      b.writeln('  return response.data as Map<String, dynamic>;');
      b.writeln('}');
      b.writeln();
    }
    return b.toString();
  }

  // ── RPC Functions ───────────────────────────────────────────────────

  /// The Dart return type for an RPC `returns:` declaration.
  String _rpcReturnType(String returns) {
    if (returns.startsWith('row:')) {
      return _className(returns.substring(4));
    }
    if (returns.startsWith('rows:')) {
      return 'List<${_className(returns.substring(5))}>';
    }
    return switch (returns) {
      'uuid' || 'text' => 'String',
      'integer' => 'int',
      'boolean' => 'bool',
      'json' => 'dynamic',
      _ => 'void',
    };
  }

  /// The table name an RPC `returns:` references, or null for scalar returns.
  String? _rpcReturnTable(String returns) {
    if (returns.startsWith('row:')) return returns.substring(4);
    if (returns.startsWith('rows:')) return returns.substring(5);
    return null;
  }

  String _generateRpc(Map<String, RpcFunctionConfig> functions) {
    final b = StringBuffer();
    b.writeln('// GENERATED by supabase_client_gen — do not edit by hand.');
    b.writeln('// Source of truth: the supabase.yaml contract.');
    b.writeln('// Typed wrappers for Postgres functions (client.rpc)');
    b.writeln();
    // `show` keeps generated table models (e.g. Session, User) from clashing
    // with the gotrue types of the same name re-exported by supabase_flutter.
    b.writeln(
      "import 'package:supabase_flutter/supabase_flutter.dart' show Supabase;",
    );
    final modelImports = functions.values
        .map((fn) => _rpcReturnTable(fn.returns))
        .whereType<String>()
        .toSet()
        .toList()
      ..sort();
    for (final table in modelImports) {
      b.writeln("import '../models/$table.dart';");
    }
    b.writeln();

    for (final entry in functions.entries) {
      _writeRpcFunction(b, entry.key, entry.value);
      b.writeln();
    }
    return b.toString();
  }

  void _writeRpcFunction(StringBuffer b, String fnName, RpcFunctionConfig fn) {
    final returnType = _rpcReturnType(fn.returns);
    final returnTable = _rpcReturnTable(fn.returns);
    final requiredArgs =
        fn.args.keys.where((a) => !fn.optionalArgs.contains(a)).toList();
    final optionalArgs =
        fn.args.keys.where((a) => fn.optionalArgs.contains(a)).toList();
    final hasArgs = fn.args.isNotEmpty;

    b.writeln('/// ${fn.description ?? 'RPC: $fnName'}');
    if (hasArgs) {
      b.writeln('Future<$returnType> ${_camel(fnName)}({');
      for (final a in requiredArgs) {
        b.writeln('  required ${_rpcArgType(fn, a)} ${_camel(a)},');
      }
      for (final a in optionalArgs) {
        b.writeln('  ${_rpcArgType(fn, a)}? ${_camel(a)},');
      }
      b.writeln('}) async {');
    } else {
      b.writeln('Future<$returnType> ${_camel(fnName)}() async {');
    }
    b.writeln('  final client = Supabase.instance.client;');
    if (hasArgs) {
      b.writeln('  final params = <String, dynamic>{');
      for (final a in requiredArgs) {
        b.writeln("    '$a': ${_rpcArgExpr(fn, a)},");
      }
      b.writeln('  };');
      // Optional args are omitted when null so Postgres DEFAULT values apply.
      for (final a in optionalArgs) {
        b.writeln(
          "  if (${_camel(a)} != null) params['$a'] = ${_rpcArgExpr(fn, a)};",
        );
      }
    }
    final call = hasArgs
        ? "client.rpc('$fnName', params: params)"
        : "client.rpc('$fnName')";
    if (fn.returns == 'void') {
      b.writeln('  await $call;');
    } else {
      b.writeln('  final result = await $call;');
      if (returnTable != null) {
        final model = _className(returnTable);
        if (fn.returns.startsWith('rows:')) {
          b.writeln('  return (result as List)');
          b.writeln(
            '      .map((j) => $model.fromJson((j as Map).cast<String, dynamic>()))',
          );
          b.writeln('      .toList();');
        } else {
          b.writeln(
            '  return $model.fromJson((result as Map).cast<String, dynamic>());',
          );
        }
      } else {
        b.writeln(switch (fn.returns) {
          'uuid' || 'text' => '  return result as String;',
          'integer' => '  return (result as num).toInt();',
          'boolean' => '  return result as bool;',
          _ => '  return result;', // json → dynamic
        });
      }
    }
    b.writeln('}');
  }

  /// Dart parameter type for an RPC argument — same pg→Dart mapping as model
  /// fields (enums are not supported as RPC argument types).
  String _rpcArgType(RpcFunctionConfig fn, String arg) =>
      tryMapPgScalarType(fn.args[arg] ?? 'text') ?? 'String';

  /// Expression placed into the params map for an RPC argument. Optional args
  /// sit inside a `!= null` guard, where the local promotes to non-nullable.
  String _rpcArgExpr(RpcFunctionConfig fn, String arg) {
    final c = _camel(arg);
    if (_rpcArgType(fn, arg) == 'DateTime') return '$c.toIso8601String()';
    return c;
  }

  // ── Helpers ─────────────────────────────────────────────────────────

  String _barrel(Iterable<String> exports) =>
      '// GENERATED by supabase_client_gen — do not edit by hand.\n'
      '// Source of truth: the supabase.yaml contract.\n\n'
      '${exports.join('\n')}\n';

  String _className(String tableName) => _pascal(_singular(tableName));

  bool _hasEnumFields(TableConfig table) =>
      table.fields.keys.any((f) => table.isEnumField(f));

  String _dartType(TableConfig table, String fieldName) {
    if (table.isEnumField(fieldName)) return _pascal(table.fields[fieldName]!);
    return table.dartType(fieldName);
  }

  /// Nullability comes solely from the contract's `nullable_fields`, never from
  /// ambient DB state — this is what keeps generated output deterministic and
  /// machine-independent. Use `generate --with-db --sync-nullability` to
  /// materialise the live DB's nullability into the contract beforehand.
  bool _isNullable(String tableName, String fieldName) {
    final table = contract.publicTables[tableName];
    return table?.nullableFields?.contains(fieldName) ?? false;
  }

  String _fnParamType(String pgType) => switch (pgType) {
        'uuid' || 'text' => 'String',
        'integer' || 'int4' => 'int',
        'boolean' || 'bool' => 'bool',
        'jsonb' || 'json' => 'Map<String, dynamic>',
        _ => 'String',
      };

  static const _reserved = {
    'new',
    'class',
    'enum',
    'const',
    'final',
    'var',
    'static',
    'void',
    'if',
    'else',
    'for',
    'while',
    'do',
    'switch',
    'case',
    'default',
    'break',
    'continue',
    'return',
    'throw',
    'try',
    'catch',
    'finally',
    'import',
    'export',
    'library',
    'part',
    'typedef',
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'hide',
    'show',
    'sync',
    'yield',
    'on',
    'in',
    'is',
    'operator',
    'factory',
    'get',
    'set',
    'with',
    'extends',
    'implements',
    'interface',
    'mixin',
    'super',
    'this',
    'true',
    'false',
    'null',
    'deferred',
    'dynamic',
    'covariant',
    'external',
    'Function',
    'late',
    'required',
    'sealed',
    'base',
  };

  String _safeEnum(String v) => _reserved.contains(v) ? '\$$v' : v;

  String _singular(String plural) {
    if (plural.endsWith('ies')) {
      return '${plural.substring(0, plural.length - 3)}y';
    }
    if (plural.endsWith('s') && !plural.endsWith('ss')) {
      return plural.substring(0, plural.length - 1);
    }
    return plural;
  }

  String _pascal(String s) => s
      .split(RegExp(r'[_-]'))
      .where((w) => w.isNotEmpty)
      .map((w) => w[0].toUpperCase() + w.substring(1))
      .join();

  String _camel(String s) {
    final p = _pascal(s);
    return p.isEmpty ? p : p[0].toLowerCase() + p.substring(1);
  }
}

class _Param {
  final String name;
  final String dartName;
  final bool required;
  const _Param(this.name, this.dartName, this.required);
}
