/// Markdown projection of a contract: `CONTRACT.md`.
///
/// A compact, deterministic data dictionary for IT professionals — and the
/// fastest way to hand a backend's shape to an AI or a colleague. Order
/// follows the contract; no timestamps, no ambient state: the same contract
/// always produces byte-identical Markdown.
library;

import 'contract.dart';

/// Renders the `CONTRACT.md` content for [contract].
String emitContractMarkdown(SupabaseContract contract) {
  final b = StringBuffer();

  b.writeln(
    '<!-- GENERATED by supabase_client_gen — '
    'edit the contract, not this file -->',
  );
  b.writeln();
  b.writeln('# ${contract.contract.name} v${contract.contract.version}');
  b.writeln();
  b.writeln(
    '`${contract.contract.date}` · project `${contract.project.remoteName}` '
    '· ref `${contract.project.remoteRef}`',
  );

  final summary = contract.summary;
  if (summary != null && summary.trim().isNotEmpty) {
    b.writeln();
    b.writeln(summary.trim());
  }

  _writeTables(b, contract);
  _writeRpcFunctions(b, contract);
  _writeEdgeFunctions(b, contract);
  _writeRealtime(b, contract);
  _writeStorage(b, contract);

  return b.toString();
}

// ── Tables ────────────────────────────────────────────────────────────

void _writeTables(StringBuffer b, SupabaseContract contract) {
  final tables = contract.publicTables;
  if (tables.isEmpty) return;
  b.writeln();
  b.writeln('## Tables');
  for (final entry in tables.entries) {
    _writeTable(b, entry.key, entry.value);
  }
}

void _writeTable(StringBuffer b, String tableName, TableConfig table) {
  b.writeln();
  b.writeln(table.isView ? '### $tableName `view`' : '### $tableName');
  b.writeln();
  if (table.description != null && table.description!.trim().isNotEmpty) {
    b.writeln(table.description!.trim());
    b.writeln();
  }

  b.writeln('| Field | Type | Null | Notes |');
  b.writeln('|---|---|---|---|');
  for (final field in table.fields.entries) {
    final notes = <String>[];
    if (table.primaryKey.contains(field.key)) notes.add('PK');
    if (table.isEnumField(field.key)) {
      final values = table.enumValues![field.value]!;
      notes.add('enum(${values.join(', ')})');
    }
    final nullable =
        table.nullableFields?.contains(field.key) ?? false ? '✓' : '';
    b.writeln(
      '| ${field.key} | ${field.value} | $nullable | ${notes.join(' · ')} |',
    );
  }

  final access = table.clientAccess;
  if (access != null && access.isNotEmpty) {
    b.writeln();
    final parts = access.entries.map((e) => '${e.key}: ${e.value}');
    b.writeln('`${parts.join(' · ')}`');
  }
}

// ── RPC Functions ─────────────────────────────────────────────────────

void _writeRpcFunctions(StringBuffer b, SupabaseContract contract) {
  final functions = contract.rpcFunctions;
  if (functions == null || functions.isEmpty) return;
  b.writeln();
  b.writeln('## RPC Functions');
  for (final entry in functions.entries) {
    final fn = entry.value;
    final args = fn.args.entries.map((a) {
      final opt = fn.optionalArgs.contains(a.key) ? '?' : '';
      return '${a.key}$opt: ${a.value}';
    }).join(', ');
    b.writeln();
    b.writeln('`${entry.key}($args) → ${fn.returns}`');
    if (fn.description != null && fn.description!.trim().isNotEmpty) {
      b.writeln(fn.description!.trim());
    }
  }
}

// ── Edge Functions ────────────────────────────────────────────────────

void _writeEdgeFunctions(StringBuffer b, SupabaseContract contract) {
  final functions = contract.edgeFunctions;
  if (functions == null || functions.isEmpty) return;
  b.writeln();
  b.writeln('## Edge Functions');
  for (final entry in functions.entries) {
    final fn = entry.value;
    final fields = [
      ...fn.requiredFields,
      ...fn.optionalFields.map((f) => '$f?'),
    ].join(', ');
    b.writeln();
    b.writeln('`${fn.method} ${entry.key}($fields)`');
    if (fn.description != null && fn.description!.trim().isNotEmpty) {
      b.writeln(fn.description!.trim());
    }
  }
}

// ── Realtime ──────────────────────────────────────────────────────────

void _writeRealtime(StringBuffer b, SupabaseContract contract) {
  final realtime = contract.realtime;
  if (realtime == null ||
      (realtime.allowedTables.isEmpty && realtime.events.isEmpty)) {
    return;
  }
  b.writeln();
  b.writeln('## Realtime');
  b.writeln();
  if (realtime.allowedTables.isNotEmpty) {
    final tables = realtime.allowedTables.map((t) => '`$t`').join(', ');
    b.writeln('Publication: $tables');
  }
  for (final event in realtime.events) {
    b.writeln(
      '- `${event.name}` ← `${event.source}` (audience: ${event.audience})',
    );
  }
}

// ── Storage ───────────────────────────────────────────────────────────

void _writeStorage(StringBuffer b, SupabaseContract contract) {
  final storage = contract.storage;
  if (storage == null || storage.buckets.isEmpty) return;
  b.writeln();
  b.writeln('## Storage');
  b.writeln();
  for (final entry in storage.buckets.entries) {
    final bk = entry.value;
    final parts = <String>[
      bk.public ? 'public' : 'private',
      if (bk.allowedMimeTypes.isNotEmpty) bk.allowedMimeTypes.join(', '),
      if (bk.fileSizeLimitMb != null) 'max ${bk.fileSizeLimitMb} MB',
    ];
    b.writeln('- `${entry.key}` — ${parts.join(' · ')}');
  }
}
