// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.sessions

import 'package:equatable/equatable.dart';

class Session extends Equatable {
  const Session({
    required this.id,
    required this.code,
    required this.createdAt,
  });

  final String id;
  final String code;
  final DateTime createdAt;

  Session copyWith({String? id, String? code, DateTime? createdAt}) {
    return Session(
      id: id ?? this.id,
      code: code ?? this.code,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory Session.fromJson(Map<String, dynamic> json) {
    return Session(
      id: json['id'] as String? ?? '',
      code: json['code'] as String? ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {'id': id, 'code': code, 'created_at': createdAt.toIso8601String()};
  }

  @override
  List<Object?> get props => [id, code, createdAt];
}
