// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// View: public.session_queue_overview (read-only)

import 'package:equatable/equatable.dart';

class SessionQueueOverview extends Equatable {
  const SessionQueueOverview({
    required this.id,
    required this.sessionId,
    required this.title,
    required this.voteCount,
  });

  final String id;
  final String sessionId;
  final String title;
  final int voteCount;

  SessionQueueOverview copyWith({
    String? id,
    String? sessionId,
    String? title,
    int? voteCount,
  }) {
    return SessionQueueOverview(
      id: id ?? this.id,
      sessionId: sessionId ?? this.sessionId,
      title: title ?? this.title,
      voteCount: voteCount ?? this.voteCount,
    );
  }

  factory SessionQueueOverview.fromJson(Map<String, dynamic> json) {
    return SessionQueueOverview(
      id: json['id'] as String? ?? '',
      sessionId: json['session_id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      voteCount: (json['vote_count'] as num?)?.toInt() ?? 0,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'session_id': sessionId,
      'title': title,
      'vote_count': voteCount,
    };
  }

  @override
  List<Object?> get props => [id, sessionId, title, voteCount];
}
