// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.session_players

import 'package:equatable/equatable.dart';

class SessionPlayer extends Equatable {
  const SessionPlayer({
    required this.sessionId,
    required this.userId,
    required this.role,
    required this.joinedAt,
  });

  final String sessionId;
  final String userId;
  final String role;
  final DateTime joinedAt;

  SessionPlayer copyWith({
    String? sessionId,
    String? userId,
    String? role,
    DateTime? joinedAt,
  }) {
    return SessionPlayer(
      sessionId: sessionId ?? this.sessionId,
      userId: userId ?? this.userId,
      role: role ?? this.role,
      joinedAt: joinedAt ?? this.joinedAt,
    );
  }

  factory SessionPlayer.fromJson(Map<String, dynamic> json) {
    return SessionPlayer(
      sessionId: json['session_id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      role: json['role'] as String? ?? '',
      joinedAt: json['joined_at'] != null
          ? DateTime.parse(json['joined_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'session_id': sessionId,
      'user_id': userId,
      'role': role,
      'joined_at': joinedAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [sessionId, userId, role, joinedAt];
}
