// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.songs

import 'package:equatable/equatable.dart';

class Song extends Equatable {
  const Song({
    required this.id,
    required this.sessionId,
    required this.title,
    required this.duration,
    this.thumbnailUrl,
  });

  final String id;
  final String sessionId;
  final String title;
  final int duration;
  final String? thumbnailUrl;

  Song copyWith({
    String? id,
    String? sessionId,
    String? title,
    int? duration,
    String? thumbnailUrl,
  }) {
    return Song(
      id: id ?? this.id,
      sessionId: sessionId ?? this.sessionId,
      title: title ?? this.title,
      duration: duration ?? this.duration,
      thumbnailUrl: thumbnailUrl ?? this.thumbnailUrl,
    );
  }

  factory Song.fromJson(Map<String, dynamic> json) {
    return Song(
      id: json['id'] as String? ?? '',
      sessionId: json['session_id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      duration: (json['duration'] as num?)?.toInt() ?? 0,
      thumbnailUrl: json['thumbnail_url'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'session_id': sessionId,
      'title': title,
      'duration': duration,
      'thumbnail_url': thumbnailUrl,
    };
  }

  @override
  List<Object?> get props => [id, sessionId, title, duration, thumbnailUrl];
}
