// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Typed storage bucket clients

import 'dart:typed_data';
import 'package:supabase_flutter/supabase_flutter.dart';

/// Typed client for the `avatars` storage bucket.
class AvatarsBucket {
  static const String name = 'avatars';
  static const bool isPublic = true;
  static const List<String> allowedMimeTypes = ['image/png', 'image/jpeg'];
  static const int? fileSizeLimitBytes = 5242880;

  final SupabaseClient _client;
  const AvatarsBucket(this._client);

  StorageFileApi get _bucket => _client.storage.from(name);

  /// Uploads [bytes] to [path], validating MIME type and size.
  Future<String> upload(
    String path,
    Uint8List bytes, {
    String? contentType,
    bool upsert = true,
  }) async {
    _validate(bytes, contentType);
    return _bucket.uploadBinary(
      path,
      bytes,
      fileOptions: FileOptions(contentType: contentType, upsert: upsert),
    );
  }

  /// Downloads the object at [path].
  Future<Uint8List> download(String path) => _bucket.download(path);

  /// Public URL for [path] (this bucket is public).
  String getPublicUrl(String path) => _bucket.getPublicUrl(path);

  /// Removes the objects at [paths].
  Future<List<FileObject>> remove(List<String> paths) => _bucket.remove(paths);

  void _validate(Uint8List bytes, String? contentType) {
    if (allowedMimeTypes.isNotEmpty &&
        contentType != null &&
        !allowedMimeTypes.contains(contentType)) {
      throw ArgumentError(
        'Content type $contentType is not allowed for bucket $name. Allowed: $allowedMimeTypes',
      );
    }
    if (fileSizeLimitBytes != null && bytes.length > fileSizeLimitBytes!) {
      throw ArgumentError(
        'File size ${bytes.length} bytes exceeds the $fileSizeLimitBytes byte limit for bucket $name',
      );
    }
  }
}

/// Typed client for the `documents` storage bucket.
class DocumentsBucket {
  static const String name = 'documents';
  static const bool isPublic = false;
  static const List<String> allowedMimeTypes = ['application/pdf'];
  static const int? fileSizeLimitBytes = 26214400;

  final SupabaseClient _client;
  const DocumentsBucket(this._client);

  StorageFileApi get _bucket => _client.storage.from(name);

  /// Uploads [bytes] to [path], validating MIME type and size.
  Future<String> upload(
    String path,
    Uint8List bytes, {
    String? contentType,
    bool upsert = true,
  }) async {
    _validate(bytes, contentType);
    return _bucket.uploadBinary(
      path,
      bytes,
      fileOptions: FileOptions(contentType: contentType, upsert: upsert),
    );
  }

  /// Downloads the object at [path].
  Future<Uint8List> download(String path) => _bucket.download(path);

  /// Time-limited signed URL for [path] (private bucket).
  Future<String> createSignedUrl(String path, {int expiresIn = 3600}) =>
      _bucket.createSignedUrl(path, expiresIn);

  /// Removes the objects at [paths].
  Future<List<FileObject>> remove(List<String> paths) => _bucket.remove(paths);

  void _validate(Uint8List bytes, String? contentType) {
    if (allowedMimeTypes.isNotEmpty &&
        contentType != null &&
        !allowedMimeTypes.contains(contentType)) {
      throw ArgumentError(
        'Content type $contentType is not allowed for bucket $name. Allowed: $allowedMimeTypes',
      );
    }
    if (fileSizeLimitBytes != null && bytes.length > fileSizeLimitBytes!) {
      throw ArgumentError(
        'File size ${bytes.length} bytes exceeds the $fileSizeLimitBytes byte limit for bucket $name',
      );
    }
  }
}
