// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.attachments

import 'package:equatable/equatable.dart';

class Attachment extends Equatable {
  const Attachment({
    required this.id,
    required this.workspaceId,
    required this.ticketId,
    required this.storagePath,
    required this.mimeType,
    required this.sizeBytes,
    this.metadata,
  });

  final String id;
  final String workspaceId;
  final String ticketId;
  final String storagePath;
  final String mimeType;
  final int sizeBytes;
  final Map<String, dynamic>? metadata;

  Attachment copyWith({
    String? id,
    String? workspaceId,
    String? ticketId,
    String? storagePath,
    String? mimeType,
    int? sizeBytes,
    Map<String, dynamic>? metadata,
  }) {
    return Attachment(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      ticketId: ticketId ?? this.ticketId,
      storagePath: storagePath ?? this.storagePath,
      mimeType: mimeType ?? this.mimeType,
      sizeBytes: sizeBytes ?? this.sizeBytes,
      metadata: metadata ?? this.metadata,
    );
  }

  factory Attachment.fromJson(Map<String, dynamic> json) {
    return Attachment(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      ticketId: json['ticket_id'] as String? ?? '',
      storagePath: json['storage_path'] as String? ?? '',
      mimeType: json['mime_type'] as String? ?? '',
      sizeBytes: (json['size_bytes'] as num?)?.toInt() ?? 0,
      metadata: json['metadata'] as Map<String, dynamic>?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'ticket_id': ticketId,
      'storage_path': storagePath,
      'mime_type': mimeType,
      'size_bytes': sizeBytes,
      'metadata': metadata,
    };
  }

  @override
  List<Object?> get props => [
    id,
    workspaceId,
    ticketId,
    storagePath,
    mimeType,
    sizeBytes,
    metadata,
  ];
}
