// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.customers

import 'package:equatable/equatable.dart';

class Customer extends Equatable {
  const Customer({
    required this.id,
    required this.workspaceId,
    required this.email,
    required this.fullName,
    this.company,
  });

  final String id;
  final String workspaceId;
  final String email;
  final String fullName;
  final String? company;

  Customer copyWith({
    String? id,
    String? workspaceId,
    String? email,
    String? fullName,
    String? company,
  }) {
    return Customer(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      email: email ?? this.email,
      fullName: fullName ?? this.fullName,
      company: company ?? this.company,
    );
  }

  factory Customer.fromJson(Map<String, dynamic> json) {
    return Customer(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      email: json['email'] as String? ?? '',
      fullName: json['full_name'] as String? ?? '',
      company: json['company'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'email': email,
      'full_name': fullName,
      'company': company,
    };
  }

  @override
  List<Object?> get props => [id, workspaceId, email, fullName, company];
}
