// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.knowledge_articles

import 'package:equatable/equatable.dart';

class KnowledgeArticle extends Equatable {
  const KnowledgeArticle({
    required this.articleId,
    required this.workspaceId,
    required this.title,
    required this.body,
    this.embedding,
    required this.published,
    required this.updatedAt,
  });

  final String articleId;
  final String workspaceId;
  final String title;
  final String body;
  final List<double>? embedding;
  final bool published;
  final DateTime updatedAt;

  KnowledgeArticle copyWith({
    String? articleId,
    String? workspaceId,
    String? title,
    String? body,
    List<double>? embedding,
    bool? published,
    DateTime? updatedAt,
  }) {
    return KnowledgeArticle(
      articleId: articleId ?? this.articleId,
      workspaceId: workspaceId ?? this.workspaceId,
      title: title ?? this.title,
      body: body ?? this.body,
      embedding: embedding ?? this.embedding,
      published: published ?? this.published,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  factory KnowledgeArticle.fromJson(Map<String, dynamic> json) {
    return KnowledgeArticle(
      articleId: json['article_id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      title: json['title'] as String? ?? '',
      body: json['body'] as String? ?? '',
      embedding: json['embedding'] as List<double>?,
      published: json['published'] as bool? ?? false,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'article_id': articleId,
      'workspace_id': workspaceId,
      'title': title,
      'body': body,
      'embedding': embedding,
      'published': published,
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [
    articleId,
    workspaceId,
    title,
    body,
    embedding,
    published,
    updatedAt,
  ];
}
