// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

export 'profiles.dart';
export 'workspaces.dart';
export 'workspace_members.dart';
export 'customers.dart';
export 'tickets.dart';
export 'ticket_comments.dart';
export 'tags.dart';
export 'knowledge_articles.dart';
export 'attachments.dart';
export 'announcements.dart';
export 'notifications.dart';
export 'audit_log.dart';
