// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.profiles

import 'package:equatable/equatable.dart';

class Profile extends Equatable {
  const Profile({
    required this.id,
    required this.displayName,
    this.avatarUrl,
    this.locale,
    required this.createdAt,
  });

  final String id;
  final String displayName;
  final String? avatarUrl;
  final String? locale;
  final DateTime createdAt;

  Profile copyWith({
    String? id,
    String? displayName,
    String? avatarUrl,
    String? locale,
    DateTime? createdAt,
  }) {
    return Profile(
      id: id ?? this.id,
      displayName: displayName ?? this.displayName,
      avatarUrl: avatarUrl ?? this.avatarUrl,
      locale: locale ?? this.locale,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory Profile.fromJson(Map<String, dynamic> json) {
    return Profile(
      id: json['id'] as String? ?? '',
      displayName: json['display_name'] as String? ?? '',
      avatarUrl: json['avatar_url'] as String?,
      locale: json['locale'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'display_name': displayName,
      'avatar_url': avatarUrl,
      'locale': locale,
      'created_at': createdAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [id, displayName, avatarUrl, locale, createdAt];
}
