// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.tags

import 'package:equatable/equatable.dart';

class Tag extends Equatable {
  const Tag({
    required this.id,
    required this.workspaceId,
    required this.label,
    this.color,
  });

  final String id;
  final String workspaceId;
  final String label;
  final String? color;

  Tag copyWith({
    String? id,
    String? workspaceId,
    String? label,
    String? color,
  }) {
    return Tag(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      label: label ?? this.label,
      color: color ?? this.color,
    );
  }

  factory Tag.fromJson(Map<String, dynamic> json) {
    return Tag(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      label: json['label'] as String? ?? '',
      color: json['color'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'label': label,
      'color': color,
    };
  }

  @override
  List<Object?> get props => [id, workspaceId, label, color];
}
