// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.tickets

import 'package:equatable/equatable.dart';
import '../enums/enums.dart';

class Ticket extends Equatable {
  const Ticket({
    required this.id,
    required this.workspaceId,
    required this.customerId,
    required this.subject,
    required this.status,
    required this.priority,
    this.assigneeId,
    this.satisfaction,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String workspaceId;
  final String customerId;
  final String subject;
  final TicketStatus status;
  final TicketPriority priority;
  final String? assigneeId;
  final double? satisfaction;
  final DateTime createdAt;
  final DateTime updatedAt;

  Ticket copyWith({
    String? id,
    String? workspaceId,
    String? customerId,
    String? subject,
    TicketStatus? status,
    TicketPriority? priority,
    String? assigneeId,
    double? satisfaction,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Ticket(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      customerId: customerId ?? this.customerId,
      subject: subject ?? this.subject,
      status: status ?? this.status,
      priority: priority ?? this.priority,
      assigneeId: assigneeId ?? this.assigneeId,
      satisfaction: satisfaction ?? this.satisfaction,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  factory Ticket.fromJson(Map<String, dynamic> json) {
    return Ticket(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      customerId: json['customer_id'] as String? ?? '',
      subject: json['subject'] as String? ?? '',
      status: TicketStatus.fromString(json['status'] as String? ?? ''),
      priority: TicketPriority.fromString(json['priority'] as String? ?? ''),
      assigneeId: json['assignee_id'] as String?,
      satisfaction: (json['satisfaction'] as num?)?.toDouble(),
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'customer_id': customerId,
      'subject': subject,
      'status': status.name,
      'priority': priority.name,
      'assignee_id': assigneeId,
      'satisfaction': satisfaction,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [
    id,
    workspaceId,
    customerId,
    subject,
    status,
    priority,
    assigneeId,
    satisfaction,
    createdAt,
    updatedAt,
  ];
}
