// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.ticket_comments

import 'package:equatable/equatable.dart';

class TicketComment extends Equatable {
  const TicketComment({
    required this.id,
    required this.workspaceId,
    required this.ticketId,
    required this.authorId,
    required this.body,
    required this.isInternal,
    required this.createdAt,
  });

  final String id;
  final String workspaceId;
  final String ticketId;
  final String authorId;
  final String body;
  final bool isInternal;
  final DateTime createdAt;

  TicketComment copyWith({
    String? id,
    String? workspaceId,
    String? ticketId,
    String? authorId,
    String? body,
    bool? isInternal,
    DateTime? createdAt,
  }) {
    return TicketComment(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      ticketId: ticketId ?? this.ticketId,
      authorId: authorId ?? this.authorId,
      body: body ?? this.body,
      isInternal: isInternal ?? this.isInternal,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory TicketComment.fromJson(Map<String, dynamic> json) {
    return TicketComment(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      ticketId: json['ticket_id'] as String? ?? '',
      authorId: json['author_id'] as String? ?? '',
      body: json['body'] as String? ?? '',
      isInternal: json['is_internal'] as bool? ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'ticket_id': ticketId,
      'author_id': authorId,
      'body': body,
      'is_internal': isInternal,
      'created_at': createdAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [
    id,
    workspaceId,
    ticketId,
    authorId,
    body,
    isInternal,
    createdAt,
  ];
}
