// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.workspace_members

import 'package:equatable/equatable.dart';

class WorkspaceMember extends Equatable {
  const WorkspaceMember({
    required this.id,
    required this.workspaceId,
    required this.userId,
    required this.role,
    this.invitedBy,
    this.joinedAt,
  });

  final String id;
  final String workspaceId;
  final String userId;
  final String role;
  final String? invitedBy;
  final DateTime? joinedAt;

  WorkspaceMember copyWith({
    String? id,
    String? workspaceId,
    String? userId,
    String? role,
    String? invitedBy,
    DateTime? joinedAt,
  }) {
    return WorkspaceMember(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      userId: userId ?? this.userId,
      role: role ?? this.role,
      invitedBy: invitedBy ?? this.invitedBy,
      joinedAt: joinedAt ?? this.joinedAt,
    );
  }

  factory WorkspaceMember.fromJson(Map<String, dynamic> json) {
    return WorkspaceMember(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      userId: json['user_id'] as String? ?? '',
      role: json['role'] as String? ?? '',
      invitedBy: json['invited_by'] as String?,
      joinedAt: json['joined_at'] != null
          ? DateTime.parse(json['joined_at'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'user_id': userId,
      'role': role,
      'invited_by': invitedBy,
      'joined_at': joinedAt?.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [
    id,
    workspaceId,
    userId,
    role,
    invitedBy,
    joinedAt,
  ];
}
