// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.workspaces

import 'package:equatable/equatable.dart';
import '../enums/enums.dart';

class Workspace extends Equatable {
  const Workspace({
    required this.id,
    required this.name,
    required this.plan,
    required this.createdAt,
  });

  final String id;
  final String name;
  final WorkspacePlan plan;
  final DateTime createdAt;

  Workspace copyWith({
    String? id,
    String? name,
    WorkspacePlan? plan,
    DateTime? createdAt,
  }) {
    return Workspace(
      id: id ?? this.id,
      name: name ?? this.name,
      plan: plan ?? this.plan,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory Workspace.fromJson(Map<String, dynamic> json) {
    return Workspace(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      plan: WorkspacePlan.fromString(json['plan'] as String? ?? ''),
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'plan': plan.name,
      'created_at': createdAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [id, name, plan, createdAt];
}
