// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Client-invoked edge functions

import 'package:supabase_flutter/supabase_flutter.dart';

/// Create a ticket and notify the assignee.
Future<Map<String, dynamic>> createTicket({
  required String workspaceId,
  required String subject,
  String? priority,
  String? customerId,
}) async {
  final client = Supabase.instance.client;
  final response = await client.functions.invoke(
    'create_ticket',
    method: HttpMethod.post,
    body: {
      'workspace_id': workspaceId,
      'subject': subject,
      'priority': priority,
      'customer_id': customerId,
    },
  );
  return response.data as Map<String, dynamic>;
}

/// Semantic search over the knowledge base.
Future<Map<String, dynamic>> searchArticles({
  required String workspaceId,
  required String query,
}) async {
  final client = Supabase.instance.client;
  final response = await client.functions.invoke(
    'search_articles',
    method: HttpMethod.post,
    body: {'workspace_id': workspaceId, 'query': query},
  );
  return response.data as Map<String, dynamic>;
}
