// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.session_players
// Access: select=authenticated insert=authenticated update=authenticated delete=authenticated
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/session_players.dart';

class SessionPlayerRepository {
  final SupabaseClient _client;
  const SessionPlayerRepository(this._client);

  /// Select: authenticated
  Future<List<SessionPlayer>> select({int limit = 50, int offset = 0}) async {
    var query = _client.from('session_players').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => SessionPlayer.fromJson(j)).toList();
  }

  /// Insert: authenticated
  Future<SessionPlayer> insert(Map<String, dynamic> data) async {
    final row = await _client
        .from('session_players')
        .insert(data)
        .select()
        .single();
    return SessionPlayer.fromJson(row);
  }

  /// Update: authenticated
  Future<SessionPlayer> update(
    String sessionId,
    String userId,
    Map<String, dynamic> data,
  ) async {
    final row = await _client
        .from('session_players')
        .update(data)
        .eq('session_id', sessionId)
        .eq('user_id', userId)
        .select()
        .single();
    return SessionPlayer.fromJson(row);
  }

  /// Delete: authenticated
  Future<void> delete(String sessionId, String userId) async {
    await _client
        .from('session_players')
        .delete()
        .eq('session_id', sessionId)
        .eq('user_id', userId);
  }

  /// Realtime stream of changes to this table.
  Stream<List<SessionPlayer>> stream() {
    return _client
        .from('session_players')
        .stream(primaryKey: ['session_id', 'user_id'])
        .map(
          (records) => (records as List)
              .map((j) => SessionPlayer.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
