// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// View: public.session_queue_overview (read-only)
// Access: select=authenticated — views never generate insert/update/delete

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/session_queue_overview.dart';

class SessionQueueOverviewRepository {
  final SupabaseClient _client;
  const SessionQueueOverviewRepository(this._client);

  /// Select: authenticated
  Future<List<SessionQueueOverview>> select({
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('session_queue_overview').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => SessionQueueOverview.fromJson(j)).toList();
  }
}
