// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.songs
// Access: select=authenticated insert=authenticated update=authenticated delete=authenticated
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/songs.dart';

class SongRepository {
  final SupabaseClient _client;
  const SongRepository(this._client);

  /// Select: authenticated
  Future<List<Song>> select({int limit = 50, int offset = 0}) async {
    var query = _client.from('songs').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Song.fromJson(j)).toList();
  }

  /// Insert: authenticated
  Future<Song> insert(Map<String, dynamic> data) async {
    final row = await _client.from('songs').insert(data).select().single();
    return Song.fromJson(row);
  }

  /// Update: authenticated
  Future<Song> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('songs')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Song.fromJson(row);
  }

  /// Delete: authenticated
  Future<void> delete(String id) async {
    await _client.from('songs').delete().eq('id', id);
  }

  /// Realtime stream of changes to this table.
  Stream<List<Song>> stream() {
    return _client
        .from('songs')
        .stream(primaryKey: ['id'])
        .map(
          (records) => (records as List)
              .map((j) => Song.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
