// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.audit_log

import 'package:equatable/equatable.dart';

class AuditLog extends Equatable {
  const AuditLog({
    required this.id,
    required this.action,
    required this.createdAt,
  });

  final String id;
  final String action;
  final DateTime createdAt;

  AuditLog copyWith({String? id, String? action, DateTime? createdAt}) {
    return AuditLog(
      id: id ?? this.id,
      action: action ?? this.action,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  factory AuditLog.fromJson(Map<String, dynamic> json) {
    return AuditLog(
      id: json['id'] as String? ?? '',
      action: json['action'] as String? ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'action': action,
      'created_at': createdAt.toIso8601String(),
    };
  }

  @override
  List<Object?> get props => [id, action, createdAt];
}
