// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.drafts

import 'package:equatable/equatable.dart';

class Draft extends Equatable {
  const Draft({
    required this.id,
    required this.workspaceId,
    this.note,
    this.payload,
    this.embedding,
  });

  final String id;
  final String workspaceId;
  final String? note;
  final Map<String, dynamic>? payload;
  final List<double>? embedding;

  Draft copyWith({
    String? id,
    String? workspaceId,
    String? note,
    Map<String, dynamic>? payload,
    List<double>? embedding,
  }) {
    return Draft(
      id: id ?? this.id,
      workspaceId: workspaceId ?? this.workspaceId,
      note: note ?? this.note,
      payload: payload ?? this.payload,
      embedding: embedding ?? this.embedding,
    );
  }

  factory Draft.fromJson(Map<String, dynamic> json) {
    return Draft(
      id: json['id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      note: json['note'] as String?,
      payload: json['payload'] as Map<String, dynamic>?,
      embedding: json['embedding'] as List<double>?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'workspace_id': workspaceId,
      'note': note,
      'payload': payload,
      'embedding': embedding,
    };
  }

  @override
  List<Object?> get props => [id, workspaceId, note, payload, embedding];
}
