// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

export 'widgets.dart';
export 'announcements.dart';
export 'categories.dart';
export 'drafts.dart';
export 'audit_log.dart';
