// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.widgets

import 'package:equatable/equatable.dart';
import '../enums/enums.dart';

class Widget extends Equatable {
  const Widget({
    required this.widgetId,
    required this.workspaceId,
    this.label,
    required this.status,
    required this.weight,
    required this.active,
  });

  final String widgetId;
  final String workspaceId;
  final String? label;
  final WidgetStatus status;
  final double weight;
  final bool active;

  Widget copyWith({
    String? widgetId,
    String? workspaceId,
    String? label,
    WidgetStatus? status,
    double? weight,
    bool? active,
  }) {
    return Widget(
      widgetId: widgetId ?? this.widgetId,
      workspaceId: workspaceId ?? this.workspaceId,
      label: label ?? this.label,
      status: status ?? this.status,
      weight: weight ?? this.weight,
      active: active ?? this.active,
    );
  }

  factory Widget.fromJson(Map<String, dynamic> json) {
    return Widget(
      widgetId: json['widget_id'] as String? ?? '',
      workspaceId: json['workspace_id'] as String? ?? '',
      label: json['label'] as String?,
      status: WidgetStatus.fromString(json['status'] as String? ?? ''),
      weight: (json['weight'] as num?)?.toDouble() ?? 0.0,
      active: json['active'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'widget_id': widgetId,
      'workspace_id': workspaceId,
      'label': label,
      'status': status.name,
      'weight': weight,
      'active': active,
    };
  }

  @override
  List<Object?> get props => [
    widgetId,
    workspaceId,
    label,
    status,
    weight,
    active,
  ];
}
