// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Client-invoked edge functions

import 'package:supabase_flutter/supabase_flutter.dart';

/// Resolve a widget from a label.
Future<Map<String, dynamic>> resolveWidget({
  required String label,
  String? workspaceId,
}) async {
  final client = Supabase.instance.client;
  final response = await client.functions.invoke(
    'resolve_widget',
    method: HttpMethod.post,
    body: {'label': label, 'workspace_id': workspaceId},
  );
  return response.data as Map<String, dynamic>;
}

/// Publish an announcement.
Future<Map<String, dynamic>> publishAnnouncement({
  required String title,
  required String body,
}) async {
  final client = Supabase.instance.client;
  final response = await client.functions.invoke(
    'publish_announcement',
    method: HttpMethod.post,
    body: {'title': title, 'body': body},
  );
  return response.data as Map<String, dynamic>;
}
