// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.announcements
// Access: select=authenticated insert=edge_function_only update=edge_function_only delete=edge_function_only
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/announcements.dart';

class AnnouncementRepository {
  final SupabaseClient _client;
  const AnnouncementRepository(this._client);

  /// Select: authenticated
  Future<List<Announcement>> select({int limit = 50, int offset = 0}) async {
    var query = _client.from('announcements').select();
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Announcement.fromJson(j)).toList();
  }

  /// Realtime stream of changes to this table.
  Stream<List<Announcement>> stream() {
    return _client
        .from('announcements')
        .stream(primaryKey: ['id'])
        .map(
          (records) => (records as List)
              .map((j) => Announcement.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
