// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.categories
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=member_of_workspace

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/categories.dart';

class CategoryRepository {
  final SupabaseClient _client;
  const CategoryRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Category>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('categories').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Category.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<Category> insert(Map<String, dynamic> data) async {
    final row = await _client.from('categories').insert(data).select().single();
    return Category.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<Category> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('categories')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Category.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String id) async {
    await _client.from('categories').delete().eq('id', id);
  }
}
