// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.drafts
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=member_of_workspace

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart' show SupabaseClient;
import '../models/drafts.dart';

class DraftRepository {
  final SupabaseClient _client;
  const DraftRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Draft>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('drafts').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Draft.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<Draft> insert(Map<String, dynamic> data) async {
    final row = await _client.from('drafts').insert(data).select().single();
    return Draft.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<Draft> update(String id, Map<String, dynamic> data) async {
    final row = await _client
        .from('drafts')
        .update(data)
        .eq('id', id)
        .select()
        .single();
    return Draft.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String id) async {
    await _client.from('drafts').delete().eq('id', id);
  }
}
