// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.

export 'widgets_repository.dart';
export 'announcements_repository.dart';
export 'categories_repository.dart';
export 'drafts_repository.dart';
