// GENERATED by supabase_client_gen — do not edit by hand.
// Source of truth: the supabase.yaml contract.
// Table: public.widgets
// Access: select=member_of_workspace insert=member_of_workspace update=member_of_workspace delete=member_of_workspace
// Realtime: enabled

import 'dart:async';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/widgets.dart';

class WidgetRepository {
  final SupabaseClient _client;
  const WidgetRepository(this._client);

  /// Select: member_of_workspace
  Future<List<Widget>> select({
    required String workspaceId,
    int limit = 50,
    int offset = 0,
  }) async {
    var query = _client.from('widgets').select();
    query = query.eq('workspace_id', workspaceId);
    final data = await query.limit(limit).range(offset, offset + limit - 1);
    return (data as List).map((j) => Widget.fromJson(j)).toList();
  }

  /// Insert: member_of_workspace
  Future<Widget> insert(Map<String, dynamic> data) async {
    final row = await _client.from('widgets').insert(data).select().single();
    return Widget.fromJson(row);
  }

  /// Update: member_of_workspace
  Future<Widget> update(String widgetId, Map<String, dynamic> data) async {
    final row = await _client
        .from('widgets')
        .update(data)
        .eq('widget_id', widgetId)
        .select()
        .single();
    return Widget.fromJson(row);
  }

  /// Delete: member_of_workspace
  Future<void> delete(String widgetId) async {
    await _client.from('widgets').delete().eq('widget_id', widgetId);
  }

  /// Realtime stream of changes to this table.
  Stream<List<Widget>> stream({required String workspaceId}) {
    return _client
        .from('widgets')
        .stream(primaryKey: ['widget_id'])
        .eq('workspace_id', workspaceId)
        .map(
          (records) => (records as List)
              .map((j) => Widget.fromJson(j as Map<String, dynamic>))
              .toList(),
        );
  }
}
